eureka:
  instance:
    hostname: 10.10.52.24
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://10.10.52.24:8082/realms/shop
        registration:
          keycloak:
            client-id: shop-eureka-server
            client-secret: HPeL35h2fdwAD8jk9Nk6zQK02MboDVne
            scope:
              - openid
              - microprofile-jwt
      resourceserver:
        jwt:
          issuer-uri: http://10.10.52.24:8082/realms/shop
