keycloak:
  uri: http://10.10.52.24:8082
spring:
  boot:
    admin:
      client:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.10.52.24:8082/realms/shop
      client:
        registration:
          keycloak:
            client-id: shop-catalogue-service
            client-secret: a8qLbOvLNFJBllER5VOCplEgXKBqbibQ
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: shop-catalogue-service
            client-secret: a8qLbOvLNFJBllER5VOCplEgXKBqbibQ
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://10.10.52.24:8082/realms/shop
logging:
  level:
    sql: info
springdoc:
  swagger-ui:
    oauth:
      client-id: shop-catalogue-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.10.52.24:8761/eureka/
    registry-fetch-interval-seconds: 1
    register-with-eureka: true