spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.10.52.24:8082/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://10.10.52.24:8082/realms/shop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: shop-admin-service
            client-secret: EN5AyCPXSRascr4YQbRN4dwZSOXBNJIk
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: shop-admin-service
            client-secret: EN5AyCPXSRascr4YQbRN4dwZSOXBNJIk
          discovery:
            provider: keycloak
            client-id: shop-admin-service
            client-secret: EN5AyCPXSRascr4YQbRN4dwZSOXBNJIk
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.10.52.24:8761/eureka/
    register-with-eureka: false