shop:
  services:
    catalogue:
      url: lb://shop-catalogue-service
      registrationId: keycloak
spring:
  application:
    name: shop-manager-app
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.10.52.24:8082/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://10.10.52.24:8082/realms/shop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: shop-manager-app
            client-secret: kSD2JiFnjFyKimlGWzlgeaCV72P7gmcy
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: shop-manager-app
            client-secret: kSD2JiFnjFyKimlGWzlgeaCV72P7gmcy
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: shop-manager-app
            client-secret: kSD2JiFnjFyKimlGWzlgeaCV72P7gmcy
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    hostname: 10.10.52.24
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    service-url:
      defaultZone: http://10.10.52.24:8761/eureka/
    registry-fetch-interval-seconds: 1
    register-with-eureka: true
